-- Selective Data Clearing Script
-- Choose which sections to run based on what you want to clear

-- Option 1: Clear only signals (keep sessions and stocks)
-- DELETE FROM signals;

-- Option 2: Clear signals older than X days
-- DELETE FROM signals WHERE created_at < NOW() - INTERVAL '7 days';

-- Option 3: Clear signals for a specific session
-- DELETE FROM signals 
-- WHERE stock_id IN (
--     SELECT id FROM stocks WHERE session_id = 'your-session-id-here'
-- );

-- Option 4: Clear all data for a specific date
-- DELETE FROM signals 
-- WHERE stock_id IN (
--     SELECT stocks.id FROM stocks 
--     JOIN sessions ON stocks.session_id = sessions.id 
--     WHERE sessions.session_date = '2024-01-15'
-- );
-- 
-- DELETE FROM stocks 
-- WHERE session_id IN (
--     SELECT id FROM sessions WHERE session_date = '2024-01-15'
-- );
-- 
-- DELETE FROM sessions WHERE session_date = '2024-01-15';

-- Option 5: Clear only test data (if you have test sessions)
-- DELETE FROM signals 
-- WHERE stock_id IN (
--     SELECT stocks.id FROM stocks 
--     JOIN sessions ON stocks.session_id = sessions.id 
--     WHERE sessions.title LIKE '%test%' OR sessions.title LIKE '%Test%'
-- );
-- 
-- DELETE FROM stocks 
-- WHERE session_id IN (
--     SELECT id FROM sessions 
--     WHERE title LIKE '%test%' OR title LIKE '%Test%'
-- );
-- 
-- DELETE FROM sessions 
-- WHERE title LIKE '%test%' OR title LIKE '%Test%';

-- Option 6: Clear signals but keep the latest one for each stock
-- DELETE FROM signals s1
-- WHERE s1.created_at < (
--     SELECT MAX(s2.created_at) 
--     FROM signals s2 
--     WHERE s2.stock_id = s1.stock_id
-- );

-- Verification queries (uncomment to check data)
-- SELECT COUNT(*) as total_sessions FROM sessions;
-- SELECT COUNT(*) as total_stocks FROM stocks;  
-- SELECT COUNT(*) as total_signals FROM signals;
-- 
-- -- Show recent data
-- SELECT 
--     s.title as session_title,
--     st.symbol,
--     sg.signal,
--     sg.created_at
-- FROM sessions s
-- JOIN stocks st ON s.id = st.session_id
-- LEFT JOIN signals sg ON st.id = sg.stock_id
-- ORDER BY sg.created_at DESC
-- LIMIT 10; 